# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 761ca41f2665190a5fcdf8e236911b4022bf5594fb8668803807a1295ab2623b7e8161ad2f8f0a439e122effa0b352d83a5bccfafc8d0aaa8ee1031a73439650

test:
  secret_key_base: 15c27e563f7a97ff4cea33a831244c2c7360adffbe299c5fa6257db78454a5e2c2a9f153e930057edf3d4327195c7671f253aeb26f7c714101ee609b89ffb945

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
